/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/Models/Chairs.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Chairs.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-1.48, 0, 0]}>
        <mesh geometry={nodes.Cube015.geometry} material={materials.Fabric} />
        <mesh geometry={nodes.Cube015_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cube015_2.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Cube015_3.geometry} material={materials['Material.003']} />
      </group>
      <group position={[0, 1.5, 0]}>
        <mesh geometry={nodes.Cube002.geometry} material={materials.Metal} />
        <mesh geometry={nodes.Cube002_1.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Cube002_2.geometry} material={materials.Leather} />
        <mesh geometry={nodes.Cube002_3.geometry} material={materials['Leather.001']} />
      </group>
      <group position={[-0.13, 3.44, -0.65]}>
        <mesh geometry={nodes.Cylinder003_1.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cylinder003_2.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Cylinder003_3.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Cylinder003_4.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cylinder003_5.geometry} material={materials['Material.008']} />
      </group>
    </group>
  )
}

useGLTF.preload('/Chairs.glb')
