/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/Models/CoffeeMachines.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/CoffeeMachines.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.95, 0]}>
        <mesh geometry={nodes.Cylinder006.geometry} material={materials.BlackMatte} />
        <mesh geometry={nodes.Cylinder006_1.geometry} material={materials['BlackShine.Logo']} />
        <mesh geometry={nodes.Cylinder006_2.geometry} material={materials['BlackMatte.Logo']} />
        <mesh geometry={nodes.Cylinder006_3.geometry} material={materials.BlackShine} />
        <mesh geometry={nodes.Cylinder006_4.geometry} material={materials.ClearPlastic} />
        <mesh geometry={nodes.Cylinder006_5.geometry} material={materials.Water} />
      </group>
      <group position={[0, 0.51, 0]} rotation={[0, Math.PI / 2, 0]}>
        <mesh geometry={nodes.Cube001.geometry} material={materials['bottom body paint']} />
        <mesh geometry={nodes.Cube001_1.geometry} material={materials['main chrome']} />
        <mesh geometry={nodes.Cube001_2.geometry} material={materials['top buttons']} />
        <mesh geometry={nodes.Cube001_3.geometry} material={materials['cupholder chrome']} />
        <mesh geometry={nodes.Cube001_4.geometry} material={materials['air pump plastic']} />
        <mesh geometry={nodes.Cube001_5.geometry} material={materials.amblem} />
        <mesh geometry={nodes.Cube001_6.geometry} material={materials['top boddy paint']} />
        <mesh geometry={nodes.Cube001_7.geometry} material={materials['bottom glossy plastic']} />
        <mesh geometry={nodes.Cube001_8.geometry} material={materials['plastic watter tank']} />
        <mesh geometry={nodes.Cube001_9.geometry} material={materials.plastic} />
      </group>
      <mesh geometry={nodes.Main.geometry} material={materials.Red_Coffee_Machine} rotation={[0, Math.PI / 2, 0]} />
    </group>
  )
}

useGLTF.preload('/CoffeeMachines.glb')
