/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/Models/AncientStructure.glb
*/
import { useGLTF, useScroll } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import gsap from "gsap";
import React, { useLayoutEffect, useRef } from "react";

export const FLOOR_HEIGHT = 2.3;
export const NB_FLOORS = 3;

export function AncientStructure(props) {
  const { nodes, materials } = useGLTF("./Models/AncientStructure.glb");
  const ref = useRef();
  const tl = useRef();
  const firstFloorRef = useRef();
  const secondFloorRef = useRef();
  const thirdFloorRef = useRef();

  const scroll = useScroll();

  useFrame(() => {
    tl.current.seek(scroll.offset * tl.current.duration());
  });

  useLayoutEffect(() => {
    tl.current = gsap.timeline();

  

    // FIRST FLOOR ANIMATION
    tl.current.to(
      firstFloorRef.current.position,
      {
        duration: 1,
        y: -2,
        z: -7
      },
      0
    );

    //FIRST FLOOR ROTATION
    tl.current.to(
      firstFloorRef.current.rotation,
      {
        duration: 1,
        y: Math.PI / 2,
      },
      0
    );

    // SECOND FLOOR ANIMATION
    tl.current.to(
      secondFloorRef.current.position,
      {
        duration: 1,

      },
      0
    );

    // THIRD FLOOR ANIMATION
    tl.current.to(
      thirdFloorRef.current.position,
      {
        duration: 1,
        y: 2,
        x: -5,
        z: 5  
      },
      0
    );

    // THIRD FLOOR ROTATION
    tl.current.to(
      thirdFloorRef.current.rotation,
      {
        duration: 1,
        y: Math.PI / -2,
      },
      0
    );

    //FIRST FLOOR COLOR ANIMATION
    tl.current.to(
      firstFloorRef.current.material,
      {
        duration: 1,
        color: "#ff0000",
      },
      0
    );
    

      
  }, []);

  

  return (
    <group {...props} dispose={null} ref={ref}>
      <group position={[0, 0.08, 0]}>
        <group ref={thirdFloorRef}>
          <mesh
            geometry={nodes.chiki002.geometry}
            material={materials["1001"]}
            rotation={[Math.PI / 2, 0, 0]}
          />
        </group>
      </group>

      <group position={[0, 0.08, 0]}>
        <group ref={secondFloorRef}>
          <mesh
            geometry={nodes.chiki001.geometry}
            material={materials["1001"]}
            rotation={[Math.PI / 2, 0, 0]}
          />
        </group>
      </group>

      <group position={[0, 0.08, 0]}>
        <group ref={firstFloorRef}>
          <mesh
            geometry={nodes.chiki.geometry}
            material={materials["1001"]}
            rotation={[Math.PI / 2, 0, 0]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("./Models/AncientStructure.glb");
