/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/Models/Earth.glb
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Earth(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./Models/Earth.glb')
  const { actions } = useAnimations(animations, group)


  //rotate the earth on the y axis
  useEffect(() => {
    const interval = setInterval(() => {
      group.current.rotation.y += 0.004
    }, 1000 / 60)
    return () => clearInterval(interval)
  }, [])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Empty" rotation={[0, -0.03, 0.22]}>
          <group name="Clouds_2" position={[-0.68, 0, -20.5]} rotation={[3.01, 0.52, -2.89]} />
          <group name="CONT" rotation={[3.01, 0.52, -2.89]} />
          <group name="CONT_Extrude" position={[-2.64, 0.44, -0.12]} rotation={[3.01, 0.52, -2.89]} />
          <group name="LITTLE-EARTHc4dfbx" rotation={[Math.PI / 2, -0.22, -2.61]} />
          <group name="NP_Extrude" position={[-0.68, -20.51, -20.5]} rotation={[3.01, 0.52, -2.89]} />
          <group name="Ocean" position={[-0.68, 0, -20.5]} rotation={[3.01, 0.52, -2.89]} />
          <group name="RootNode" rotation={[3.01, 0.52, -2.89]} />
          <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0.22, 2.61]} />
          <group name="SP_Extrude" position={[-0.68, 20.51, -20.5]} rotation={[3.01, 0.52, -2.89]} />
          <group name="Clouds_2_Clouds_1" rotation={[0, 0.03, 0]}>
            <mesh name="Clouds_2_Clouds_1001" geometry={nodes.Clouds_2_Clouds_1001.geometry} material={materials['Clouds.001']} />
            <mesh name="Clouds_2_Clouds_1001_1" geometry={nodes.Clouds_2_Clouds_1001_1.geometry} material={materials['material.001']} />
            <mesh name="Clouds_2_Clouds_1001_2" geometry={nodes.Clouds_2_Clouds_1001_2.geometry} material={materials['Mat.001']} />
            <mesh name="Clouds_2_Clouds_1001_3" geometry={nodes.Clouds_2_Clouds_1001_3.geometry} material={materials['material_3.001']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./Models/Earth.glb')
